version: "3"

services:
  backend:
    image: ghcr.io/org/repo/image:1.0.0
    command:
      - /home/frappe/frappe-bench/env/bin/opentelemetry-instrument
      - /home/frappe/frappe-bench/env/bin/gunicorn
      - --chdir=/home/frappe/frappe-bench/sites
      - --bind=0.0.0.0:8000
      - --threads=4
      - --workers=2
      - --worker-class=gthread
      - --worker-tmp-dir=/dev/shm
      - --timeout=120
      - --preload
      - frappe_utils.app:application
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - OTEL_SERVICE_NAME=backend
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_OTLP_TRACES_PROTOCOL=grpc
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  configurator:
    image: ghcr.io/org/repo/image:1.0.0
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    # add redis_socketio for backward compatibility
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - SOCKETIO_PORT="9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: ghcr.io/org/repo/image:1.0.0
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=admin --set-default frontend;

  db:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: ghcr.io/org/repo/image:1.0.0
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      - BACKEND=backend:8000
      - FRAPPE_SITE_NAME_HEADER=frontend
      - SOCKETIO=websocket:9000
      - UPSTREAM_REAL_IP_ADDRESS=127.0.0.1
      - UPSTREAM_REAL_IP_HEADER=X-Forwarded-For
      - UPSTREAM_REAL_IP_RECURSIVE="off"
      - PROXY_READ_TIMEOUT=120
      - CLIENT_MAX_BODY_SIZE=50m
      - ENABLE_OPENTELEMETRY=1
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - ./00-otel.conf:/etc/nginx/conf.d/00-otel.conf
    ports:
      - "8080:8080"

  queue-long:
    image: ghcr.io/org/repo/image:1.0.0
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - /home/frappe/frappe-bench/env/bin/opentelemetry-instrument
      - /home/frappe/frappe-bench/env/bin/python
      - /home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py
      - frappe
      - worker
      - --queue
      - long,default,short
    environment:
      - OTEL_SERVICE_NAME=long
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_OTLP_TRACES_PROTOCOL=grpc
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    working_dir: /home/frappe/frappe-bench/sites

  queue-short:
    image: ghcr.io/org/repo/image:1.0.0
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - /home/frappe/frappe-bench/env/bin/opentelemetry-instrument
      - /home/frappe/frappe-bench/env/bin/python
      - /home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py
      - frappe
      - worker
      - --queue
      - short,default
    environment:
      - OTEL_SERVICE_NAME=short
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_OTLP_TRACES_PROTOCOL=grpc
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    working_dir: /home/frappe/frappe-bench/sites

  redis-queue:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-cache-data:/data

  scheduler:
    image: ghcr.io/org/repo/image:1.0.0
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: ghcr.io/org/repo/image:1.0.0
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  jaeger:
    image: jaegertracing/all-in-one:1.54.0
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  db-data:
  redis-queue-data:
  redis-cache-data:
  sites:
  logs:
